highlighter: pygments
permalink: /news/:title
sass:
    style: :compressed
    sass_dir: styles/_snippets
collections:
- sections
- schedule
- speakers
- volunteers
- topics
defaults:
    -
        scope:
            path: "_posts"
        values:
            layout: "news"
navigation:
  - title : "Home"
    url   : "/"
  - title : "Schedule"
    url   : "/schedule/"
#  - title : "Speakers"
#    url   : "/speakers/index.html"
#  - title : "Call for speakers"
#    url   : "/"
