permalink: /news/:title
gems:
  - jekyll-redirect-from
  - jekyll-coffeescript
sass:
    style: :compressed
#    load_paths:
    sass_dir: pages
collections:
  snippets:

defaults:
    -
        scope:
            path: "_posts"
        values:
            layout: "news"
navigation:
#  - title : "Home"
#    url   : "/"
#  - title : "Schedule"
#    url   : "/schedule/"
#  - title : "Speakers"
#    url   : "/speakers/"
#  - title : "Call For Co-Creation"
#    url   : "/call-for-co-creation/"
#  - title : "Call for speakers"
#    url   : "/"
